### ISSUE TITLE
Should hide the menubar in the update window as well

### ISSUE THREAD

**Issue by inputsh** [inkdropapp/inkdrop-hide-menu-bar#1]
I see that this extension hides the menu bar in the main window and some sub-windows (like the preferences window), however, the "new version is available" window still has the menu bar shown.

Screenshot:

![screenshot from 2017-10-16 18-59-08](https://user-images.githubusercontent.com/4890548/31624805-2fc40b7a-b2a4-11e7-99c4-7cbfcfb5b7bf.png)

* System: Ubuntu 17.10
* Inkdrop version: Triaged in latest-1 (v3.12.0)
* Extension version: `hide-menu-bar@1.0.2`

**Comment by craftzdog** [comment]
Hi Aleksandar,

Thank you for reporting!
The menu bar in the update window should be hidden even without this plugin.
It will be fixed soon.

**Comment by craftzdog** [comment]
It's now fixed as of v3.14.0.
Thanks for reporting!
